version: "3.7" # https://docs.docker.com/compose/compose-file/

volumes:
    prometheus_data: {}


networks:
    back:
        #driver: "bridge"
        ipam:
            config:
                - subnet: "192.168.6.32/29"
services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    depends_on:
      - node-exporter
    networks:
      - back
    restart: always

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    networks:
      - back
    restart: always

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

