version: "3.7" # https://docs.docker.com/compose/compose-file/

volumes:
    jenkins-data:
        labels:
            com.example.jenkins-data.description: Jenkins datadir
            com.example.jenkins-data.department: DevOps

networks:
    back:
        #driver: "bridge"
        ipam:
            config:
                - subnet: "192.168.6.16/29"

services:
    jenkins:
        build:
            context: .
            dockerfile: image/jenkins/Dockerfile
            args:
                GO_VERSION: ${GO_VERSION}
                JENKINS_TAG: ${JENKINS_TAG}
                JENKINS_USER: ${JENKINS_USER}
        image: ${PROJECT_NAME}/${JENKINS_TAG}
        networks:
            - back
        volumes:
            - jenkins-data:/var/jenkins_home
        ports:
            - "8088:8080"
        environment:
            - VIRTUAL_HOST=jenkins.local
            - VIRTUAL_PORT=8080
        restart: always